-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 20:32:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alocacao_droid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alocacao_droid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alocacao_droid` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `alocacao_droid` ;

-- -----------------------------------------------------
-- Table `alocacao_droid`.`planeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alocacao_droid`.`planeta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `tamanho` INT NOT NULL,
  `distancia` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alocacao_droid`.`droid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alocacao_droid`.`droid` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `cor_olhos` VARCHAR(45) NOT NULL,
  `forca_motor` INT NOT NULL,
  `tempo_bateria` INT NOT NULL,
  `nr_serie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alocacao_droid`.`alocacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alocacao_droid`.`alocacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL DEFAULT current_timestamp,
  `droid_id` INT NOT NULL,
  `planeta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `alocacao_droid_idx` (`droid_id` ASC),
  INDEX `alocacao_planeta_idx` (`planeta_id` ASC),
  CONSTRAINT `alocacao_droid`
    FOREIGN KEY (`droid_id`)
    REFERENCES `alocacao_droid`.`droid` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `alocacao_planeta`
    FOREIGN KEY (`planeta_id`)
    REFERENCES `alocacao_droid`.`planeta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alocacao_droid`.`manutencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alocacao_droid`.`manutencao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_servico` VARCHAR(45) NOT NULL,
  `tempo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alocacao_droid`.`atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alocacao_droid`.`atendimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `data` DATETIME NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alocacao_droid`.`conserto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alocacao_droid`.`conserto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `droid_id` INT NOT NULL,
  `atendimento_id` INT NOT NULL,
  `manutencao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `conserto_droid_idx` (`droid_id` ASC),
  INDEX `conserto_atendimento_idx` (`atendimento_id` ASC),
  INDEX `conserto_manutencao_idx` (`manutencao_id` ASC),
  CONSTRAINT `conserto_droid`
    FOREIGN KEY (`droid_id`)
    REFERENCES `alocacao_droid`.`droid` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `conserto_atendimento`
    FOREIGN KEY (`atendimento_id`)
    REFERENCES `alocacao_droid`.`atendimento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `conserto_manutencao`
    FOREIGN KEY (`manutencao_id`)
    REFERENCES `alocacao_droid`.`manutencao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alocacao_droid`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alocacao_droid`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `alocacao_droid`.`planeta`
-- -----------------------------------------------------
START TRANSACTION;
USE `alocacao_droid`;
INSERT INTO `alocacao_droid`.`planeta` (`id`, `nome`, `tamanho`, `distancia`) VALUES (1, 'Alderaan', 700, 200000);
INSERT INTO `alocacao_droid`.`planeta` (`id`, `nome`, `tamanho`, `distancia`) VALUES (2, 'Dantooine', 400, 8486511354);
INSERT INTO `alocacao_droid`.`planeta` (`id`, `nome`, `tamanho`, `distancia`) VALUES (3, 'Coruscant', 846, 234856132);
INSERT INTO `alocacao_droid`.`planeta` (`id`, `nome`, `tamanho`, `distancia`) VALUES (4, 'Tatooine', 99, 5422487524);
INSERT INTO `alocacao_droid`.`planeta` (`id`, `nome`, `tamanho`, `distancia`) VALUES (5, 'Naboo', 645, 324874123);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alocacao_droid`.`droid`
-- -----------------------------------------------------
START TRANSACTION;
USE `alocacao_droid`;
INSERT INTO `alocacao_droid`.`droid` (`id`, `nome`, `idade`, `cor_olhos`, `forca_motor`, `tempo_bateria`, `nr_serie`) VALUES (1, 'C-3PO', 15, 'larana brilhante', 5, 999, 'ABDAH');
INSERT INTO `alocacao_droid`.`droid` (`id`, `nome`, `idade`, `cor_olhos`, `forca_motor`, `tempo_bateria`, `nr_serie`) VALUES (2, 'R2-D2', 10, 'Azul eletrico', 30, 1000, 'UHUHA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `alocacao_droid`.`alocacao`
-- -----------------------------------------------------
START TRANSACTION;
USE `alocacao_droid`;
INSERT INTO `alocacao_droid`.`alocacao` (`id`, `data`, `droid_id`, `planeta_id`) VALUES (1, DEFAULT, 1, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alocacao_droid`.`manutencao`
-- -----------------------------------------------------
START TRANSACTION;
USE `alocacao_droid`;
INSERT INTO `alocacao_droid`.`manutencao` (`id`, `tipo_servico`, `tempo`) VALUES (1, 'substituicao bateria', 2);
INSERT INTO `alocacao_droid`.`manutencao` (`id`, `tipo_servico`, `tempo`) VALUES (2, 'troca motor', 8);
INSERT INTO `alocacao_droid`.`manutencao` (`id`, `tipo_servico`, `tempo`) VALUES (3, 'nova fiação', 15);
INSERT INTO `alocacao_droid`.`manutencao` (`id`, `tipo_servico`, `tempo`) VALUES (4, 'alterar olhos', 6);
INSERT INTO `alocacao_droid`.`manutencao` (`id`, `tipo_servico`, `tempo`) VALUES (5, 'troca rodas', 7);
INSERT INTO `alocacao_droid`.`manutencao` (`id`, `tipo_servico`, `tempo`) VALUES (6, 'troca pernas', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alocacao_droid`.`atendimento`
-- -----------------------------------------------------
START TRANSACTION;
USE `alocacao_droid`;
INSERT INTO `alocacao_droid`.`atendimento` (`id`, `numero`, `data`) VALUES (1, 1, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `alocacao_droid`.`conserto`
-- -----------------------------------------------------
START TRANSACTION;
USE `alocacao_droid`;
INSERT INTO `alocacao_droid`.`conserto` (`id`, `droid_id`, `atendimento_id`, `manutencao_id`) VALUES (1, 1, 1, 3);

COMMIT;

